### ISSUE TITLE
Adding "Retraining on custom data" would be Awesome.

### ISSUE THREAD

**Issue by NexusHero** [chrispolo/Mobilenet-_v1-Mask-RCNN-for-detection#2]
Thanks for the great work. The performance seems really nice. Could you add the feature to learn custom data too? That would be the icing on the cake feature

**Comment by Cpruce** [comment]
@NexusHero You can try out my PR fork https://github.com/Cpruce/Mask_RCNN, which this repo is a copy from. You should be able to fine-tune on your own dataset, assuming it is in the same format as coco. Let me know how it goes and submit an issue to my fork if it doesn't work!
